### ISSUE TITLE
please fix U2 vs U3 warning - the CPU/GPU/DDR are exactly the same

### ISSUE THREAD

**Issue by prahal** [gociii/odroid-images#4]
Could you please remove the mention that U2 has a different CPU.
They both have the same CPU (quad core).

Both U2 and U3 have:
Samsung Exynos4412 Prime Cortex-A9 Quad Core 1.7Ghz with 1MB L2 cache
2048MB(2GB) LP-DDR2 880Mega data rate
Mali-400 Quad Core 440MHz

ie even the CPU has no improved overclock between U2 and U3.
I don't remember why Hardkernel changed the number between U2 and U3 (I believe they were upping the number at each board revision at that time).

I own a U2 and have been using u3 dts for years.
The main difference is the U2 had a digital microphone on the board that is not on the U3.
I had a dts with the changes needed to support the U2 digital microphone working.
But I use this box as a headless mini server so there is no need for audio, so for this one, I use the u3 dts.

I have another U2 which I use to test Lima for the GPU and I also plan to find out why since the odroid audio driver upstream has been changed the audio quality is very poor (probably a frequency and/or a divider issue).

I do not think a warning to tell the U2 is unsupported makes technical sense, though could be the board revision is less stable due to improvements made for the U3 in the traces on the PCB... though I doubt it (maybe the current flowing back from the HDMI to the board has been fixed on the U3 but not sure it even was. Ie you had to unplug both the HDMI and the power plug to get the board to turn off when the kernel was stuck).

**Comment by gociii** [comment]
Hey prahal - thanks for that. I didn't know that as I don't have a U2. At the time of writing when I researched the internet, that was what I got. Again, thanks for the detailed explanation.
